title: false
description: "@CapsCop was an advanced Twitter bot. It searched for tweets that are in all capital letters and fired back a snarky reply to its author."
google_analytics: UA-1091244-24
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
